CREATE TABLE Appearance (id SERIAL PRIMARY KEY, text VARCHAR(255));
INSERT INTO Appearance(text) VALUES ('Distinctive jewelry: earrings, necklace, circlet, bracelets');
INSERT INTO Appearance(text) VALUES ('Piercings');
INSERT INTO Appearance(text) VALUES ('Flamboyant or outlandish clothes');
INSERT INTO Appearance(text) VALUES ('Formal, clean clothes');
INSERT INTO Appearance(text) VALUES ('Ragged, dirty clothes');
INSERT INTO Appearance(text) VALUES ('Pronounced scar');
INSERT INTO Appearance(text) VALUES ('Missing teeth');
INSERT INTO Appearance(text) VALUES ('Missing fingers');
INSERT INTO Appearance(text) VALUES ('Unusual eye color (or two different colors)');
INSERT INTO Appearance(text) VALUES ('Tattoos');
INSERT INTO Appearance(text) VALUES ('Birthmark');
INSERT INTO Appearance(text) VALUES ('Unusual skin color');
INSERT INTO Appearance(text) VALUES ('Bald');
INSERT INTO Appearance(text) VALUES ('Braided beard or hair');
INSERT INTO Appearance(text) VALUES ('Unusual hair color');
INSERT INTO Appearance(text) VALUES ('Nervous eye twitch');
INSERT INTO Appearance(text) VALUES ('Distinctive nose');
INSERT INTO Appearance(text) VALUES ('Distinctive posture (crooked or rigid)');
INSERT INTO Appearance(text) VALUES ('Exceptionally beautiful');
INSERT INTO Appearance(text) VALUES ('Exceptionally ugly');

CREATE TABLE Talent (id SERIAL PRIMARY KEY, text VARCHAR(255));
INSERT INTO Talent(text) VALUES ('Plays a musical instrument');
INSERT INTO Talent(text) VALUES ('Speaks several languages fluently');
INSERT INTO Talent(text) VALUES ('Unbelievably lucky');
INSERT INTO Talent(text) VALUES ('Perfect memory');
INSERT INTO Talent(text) VALUES ('Great with animals');
INSERT INTO Talent(text) VALUES ('Great with children');
INSERT INTO Talent(text) VALUES ('Great at solving puzzles');
INSERT INTO Talent(text) VALUES ('Great at one game');
INSERT INTO Talent(text) VALUES ('Great at impersonations');
INSERT INTO Talent(text) VALUES ('Draws beautifully');
INSERT INTO Talent(text) VALUES ('Paints beautifully');
INSERT INTO Talent(text) VALUES ('Sings beautifully');
INSERT INTO Talent(text) VALUES ('Drinks everyone under the table');
INSERT INTO Talent(text) VALUES ('Expert carpenter');
INSERT INTO Talent(text) VALUES ('Expert cook');
INSERT INTO Talent(text) VALUES ('Expert dart thrower and rock skipper');
INSERT INTO Talent(text) VALUES ('Expert juggler');
INSERT INTO Talent(text) VALUES ('Skilled actor and master of disguise');
INSERT INTO Talent(text) VALUES ('Skilled dancer');
INSERT INTO Talent(text) VALUES ('Knows thieves’ cant');