CREATE TABLE Appearance (id SERIAL PRIMARY KEY, text VARCHAR(255));
INSERT INTO Appearance(text) VALUES ('Distinctive jewelry: earrings, necklace, circlet, bracelets');
INSERT INTO Appearance(text) VALUES ('Piercings');
INSERT INTO Appearance(text) VALUES ('Flamboyant or outlandish clothes');
INSERT INTO Appearance(text) VALUES ('Formal, clean clothes');
INSERT INTO Appearance(text) VALUES ('Ragged, dirty clothes');
INSERT INTO Appearance(text) VALUES ('Pronounced scar');
INSERT INTO Appearance(text) VALUES ('Missing teeth');
INSERT INTO Appearance(text) VALUES ('Missing fingers');
INSERT INTO Appearance(text) VALUES ('Unusual eye color (or two different colors)');
INSERT INTO Appearance(text) VALUES ('Tattoos');
INSERT INTO Appearance(text) VALUES ('Birthmark');
INSERT INTO Appearance(text) VALUES ('Unusual skin color');
INSERT INTO Appearance(text) VALUES ('Bald');
INSERT INTO Appearance(text) VALUES ('Braided beard or hair');
INSERT INTO Appearance(text) VALUES ('Unusual hair color');
INSERT INTO Appearance(text) VALUES ('Nervous eye twitch');
INSERT INTO Appearance(text) VALUES ('Distinctive nose');
INSERT INTO Appearance(text) VALUES ('Distinctive posture (crooked or rigid)');
INSERT INTO Appearance(text) VALUES ('Exceptionally beautiful');
INSERT INTO Appearance(text) VALUES ('Exceptionally ugly');

CREATE TABLE Talent (id SERIAL PRIMARY KEY, text VARCHAR(255));
INSERT INTO Talent(text) VALUES ('Plays a musical instrument');
INSERT INTO Talent(text) VALUES ('Speaks several languages fluently');
INSERT INTO Talent(text) VALUES ('Unbelievably lucky');
INSERT INTO Talent(text) VALUES ('Perfect memory');
INSERT INTO Talent(text) VALUES ('Great with animals');
INSERT INTO Talent(text) VALUES ('Great with children');
INSERT INTO Talent(text) VALUES ('Great at solving puzzles');
INSERT INTO Talent(text) VALUES ('Great at one game');
INSERT INTO Talent(text) VALUES ('Great at impersonations');
INSERT INTO Talent(text) VALUES ('Draws beautifully');
INSERT INTO Talent(text) VALUES ('Paints beautifully');
INSERT INTO Talent(text) VALUES ('Sings beautifully');
INSERT INTO Talent(text) VALUES ('Drinks everyone under the table');
INSERT INTO Talent(text) VALUES ('Expert carpenter');
INSERT INTO Talent(text) VALUES ('Expert cook');
INSERT INTO Talent(text) VALUES ('Expert dart thrower and rock skipper');
INSERT INTO Talent(text) VALUES ('Expert juggler');
INSERT INTO Talent(text) VALUES ('Skilled actor and master of disguise');
INSERT INTO Talent(text) VALUES ('Skilled dancer');
INSERT INTO Talent(text) VALUES ('Knows thieves’ cant');

CREATE TABLE Mannerism (id SERIAL PRIMARY KEY, text VARCHAR(255));
INSERT INTO Mannerism(text) VALUES ('Prone to singing, whistling, or humming quietly');
INSERT INTO Mannerism(text) VALUES ('Speaks in rhyme or some other peculiar way');
INSERT INTO Mannerism(text) VALUES ('Particularly low or high voice');
INSERT INTO Mannerism(text) VALUES ('Slurs words, lisps, or stutters');
INSERT INTO Mannerism(text) VALUES ('Enunciates overly clearly');
INSERT INTO Mannerism(text) VALUES ('Speaks loudly');
INSERT INTO Mannerism(text) VALUES ('Whispers');
INSERT INTO Mannerism(text) VALUES ('Uses flowery speech or long words');
INSERT INTO Mannerism(text) VALUES ('Frequently uses the wrong word');
INSERT INTO Mannerism(text) VALUES ('Uses colorful oaths and exclamations');
INSERT INTO Mannerism(text) VALUES ('Makes constant jokes or puns');
INSERT INTO Mannerism(text) VALUES ('Prone to predictions of doom');
INSERT INTO Mannerism(text) VALUES ('Fidgets');
INSERT INTO Mannerism(text) VALUES ('Squints');
INSERT INTO Mannerism(text) VALUES ('Stares into the distance');
INSERT INTO Mannerism(text) VALUES ('Chews something');
INSERT INTO Mannerism(text) VALUES ('Paces');
INSERT INTO Mannerism(text) VALUES ('Taps fingers');
INSERT INTO Mannerism(text) VALUES ('Bites fingernails');
INSERT INTO Mannerism(text) VALUES ('Twirls hair or tugs beard');

CREATE TABLE Interaction (id SERIAL PRIMARY KEY, text VARCHAR(255));
INSERT INTO Interaction(text) VALUES ('Argumentative');
INSERT INTO Interaction(text) VALUES ('Arrogant');
INSERT INTO Interaction(text) VALUES ('Blustering');
INSERT INTO Interaction(text) VALUES ('Rude');
INSERT INTO Interaction(text) VALUES ('Curious');
INSERT INTO Interaction(text) VALUES ('Friendly');
INSERT INTO Interaction(text) VALUES ('Honest');
INSERT INTO Interaction(text) VALUES ('Hot tempered');
INSERT INTO Interaction(text) VALUES ('Irritable');
INSERT INTO Interaction(text) VALUES ('Ponderous');
INSERT INTO Interaction(text) VALUES ('Quiet');
INSERT INTO Interaction(text) VALUES ('Suspicious');

CREATE TABLE Ideal (id SERIAL PRIMARY KEY, text VARCHAR(255), alignment VARCHAR(255));
INSERT INTO Ideal(text, alignment) VALUES ('Beauty', 'Good');
INSERT INTO Ideal(text, alignment) VALUES ('Charity', 'Good');
INSERT INTO Ideal(text, alignment) VALUES ('Greater good', 'Good');
INSERT INTO Ideal(text, alignment) VALUES ('Life', 'Good');
INSERT INTO Ideal(text, alignment) VALUES ('Respect', 'Good');
INSERT INTO Ideal(text, alignment) VALUES ('Self-sacrifice', 'Good');
INSERT INTO Ideal(text, alignment) VALUES ('Domination', 'Evil');
INSERT INTO Ideal(text, alignment) VALUES ('Greed', 'Evil');
INSERT INTO Ideal(text, alignment) VALUES ('Might', 'Evil');
INSERT INTO Ideal(text, alignment) VALUES ('Pain', 'Evil');
INSERT INTO Ideal(text, alignment) VALUES ('Retribution', 'Evil');
INSERT INTO Ideal(text, alignment) VALUES ('Slaughter', 'Evil');
INSERT INTO Ideal(text, alignment) VALUES ('Community', 'Lawful');
INSERT INTO Ideal(text, alignment) VALUES ('Fairness', 'Lawful');
INSERT INTO Ideal(text, alignment) VALUES ('Honor', 'Lawful');
INSERT INTO Ideal(text, alignment) VALUES ('Logic', 'Lawful');
INSERT INTO Ideal(text, alignment) VALUES ('Responsibility', 'Lawful');
INSERT INTO Ideal(text, alignment) VALUES ('Tradition', 'Lawful');
INSERT INTO Ideal(text, alignment) VALUES ('Change', 'Chaotic');
INSERT INTO Ideal(text, alignment) VALUES ('Creativity', 'Chaotic');
INSERT INTO Ideal(text, alignment) VALUES ('Freedom', 'Chaotic');
INSERT INTO Ideal(text, alignment) VALUES ('Independence', 'Chaotic');
INSERT INTO Ideal(text, alignment) VALUES ('No limits', 'Chaotic');
INSERT INTO Ideal(text, alignment) VALUES ('Whimsy', 'Chaotic');
INSERT INTO Ideal(text, alignment) VALUES ('Balance', 'Neutral');
INSERT INTO Ideal(text, alignment) VALUES ('Knowledge', 'Neutral');
INSERT INTO Ideal(text, alignment) VALUES ('Live and let live', 'Neutral');
INSERT INTO Ideal(text, alignment) VALUES ('Moderation', 'Neutral');
INSERT INTO Ideal(text, alignment) VALUES ('Neutrality', 'Neutral');
INSERT INTO Ideal(text, alignment) VALUES ('People', 'Neutral');
INSERT INTO Ideal(text, alignment) VALUES ('Aspiration', 'Other');
INSERT INTO Ideal(text, alignment) VALUES ('Discovery', 'Other');
INSERT INTO Ideal(text, alignment) VALUES ('Glory', 'Other');
INSERT INTO Ideal(text, alignment) VALUES ('Nation', 'Other');
INSERT INTO Ideal(text, alignment) VALUES ('Redemption', 'Other');
INSERT INTO Ideal(text, alignment) VALUES ('Self-knowledge', 'Other');

CREATE TABLE Bond (id SERIAL PRIMARY KEY, text VARCHAR(255));
INSERT INTO Bond(text) VALUES ('Dedicated to fulfilling a personal life goal');
INSERT INTO Bond(text) VALUES ('Protective of close family members');
INSERT INTO Bond(text) VALUES ('Protective of colleagues or compatriots');
INSERT INTO Bond(text) VALUES ('Loyal to a benefactor, patron, or employer');
INSERT INTO Bond(text) VALUES ('Captivated by a romantic interest');
INSERT INTO Bond(text) VALUES ('Drawn to a special place');
INSERT INTO Bond(text) VALUES ('Protective of a sentimental keepsake');
INSERT INTO Bond(text) VALUES ('Protective of a valuable possession');
INSERT INTO Bond(text) VALUES ('Out for revenge');
INSERT INTO Bond(text) VALUES ('Roll twice, ignoring results of 10');

CREATE TABLE Flaw (id SERIAL PRIMARY KEY, text VARCHAR(255));
INSERT INTO Flaw(text) VALUES ('Forbidden love or susceptibility to romance');
INSERT INTO Flaw(text) VALUES ('Enjoys decadent pleasures');
INSERT INTO Flaw(text) VALUES ('Arrogance');
INSERT INTO Flaw(text) VALUES ('Envies another creature’s possessions or station');
INSERT INTO Flaw(text) VALUES ('Overpowering greed');
INSERT INTO Flaw(text) VALUES ('Prone to rage');
INSERT INTO Flaw(text) VALUES ('Has a powerful enemy');
INSERT INTO Flaw(text) VALUES ('Specific phobia');
INSERT INTO Flaw(text) VALUES ('Shameful or scandalous history');
INSERT INTO Flaw(text) VALUES ('Secret crime or misdeed');
INSERT INTO Flaw(text) VALUES ('Possession of forbidden lore');
INSERT INTO Flaw(text) VALUES ('Foolhardy bravery');

CREATE TABLE Race (id SERIAL PRIMARY KEY, age_Formula VARCHAR(255), weight_Formula VARCHAR(255), height_Formula VARCHAR(255), character_Size VARCHAR(255));
INSERT INTO Race(age_Formula, weight_Formula, height_Formula, character_Size) VALUES ('3d27','9d20+160','8d6+50' ,'medium');